version: '3'
services:
  app:
    container_name: node-mongo-docker
    build: .
    restart: always
    ports: 
      - '80:3000'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'

    